import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center mt-20`}
            >
                <div className="flex flex-col w-1/2 gap-8">
                    <div className="text-5xl font-extrabold text-teal-600 tracking-tighter">
                        ClinicalTrials
                    </div>
                    {children}
                </div>
            </body>
        </html>
    );
}
